twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    globals:
        podcast_repository: '@App\Repository\PodcastRepository'

    
when@test:
    twig:
        strict_variables: true
